witnet/sheikah

- jest.config.js
- package.json
Add jest configuration into its own file `jest.config.js`
@aesedepece Can you check if with these changes [this issue](https://github.com/witnet/sheikah/pull/33#discussion_r189998080) is fixed?
> Add jest configuration into its own file

- .travis.yml
> ci(travis): add node 9 as test suite

- package.json
fix #85
To use npm script _jest_ and no tests needed ;-)
> fix(npm): add jest config file

- .travis.yml
- package.json
> build(node): drop support for node 7 and add node 10 to travis

- .travis.yml
- package.json
> Drop support for node 7, add node 10 to travis

- app/lib/chain/chainType.ts
- app/lib/crypto/address/p2pkh.ts
- app/lib/crypto/hash.ts
- package.json
- test/app/lib/crypto/address.spec.ts
- test/app/lib/crypto/helpers.ts
- test/app/lib/crypto/key.spec.ts
- yarn.lock
> Bech32 addresses derivation

- app/lib/utils/appError.ts
> feat: implement generic Error factory

- package.json
Run `yarn clean` before running end-to-end tests to avoid false positives due to old compiled files being present in the `dist` directory. This change doesn't need tests.
> build(npm): clean before executing e2e tests

- package.json
Fix lint task in `package.json`
> build(npm): change declaration of lint task

- app/lib/encoding/slip32.ts
- package.json
- test/app/lib/encoding/fixtures.ts
- test/app/lib/encoding/slip32.spec.ts
- yarn.lock
It implements private and public key exchange capabilities using slip32 and bech32 serialization.
Closes #78 
> feat(encoding):  implement private and public key exchange format

- app/lib/chain/chainType.ts
- app/lib/crypto/address/p2pkh.ts
- test/app/lib/crypto/address.spec.ts
- tslint.json
> feat(crypto): support P2PKH Bech32 address decoding

- docs/STYLEGUIDE.md
> docs(styleguide): clarify policy regarding dependencies and devDependencies

- .hound.yml
Update hound's scss config by sass-lint config to solve css grid compatibility. No test included because commit just update a config file.
> ci: ci(hound) update hound's sccs config by sass-lint config

- package.json
Update lint staged to run yarn ts-lint for typescript files and sass-lint for sass files. No test provided because update lint config.
> build: add yarn ts-lint task and update lint-staged to run scss and ts

- config/sass-lint.yml
Update sass-lint config to use double quotes. No test provided because update lint config.
> build(sass-lint) update sass-lint config to use double quotes

- app/main/ciphers/aes.ts
- app/main/ciphers/index.ts
- test/app/main/ciphers/aes.fixtures.ts
- test/app/main/ciphers/aes.spec.ts
- Adds AES cipher for future use as a subsystem or as part of a subsystem.
- Adds tests for AES cipher.
>  feat(subsystem): add AES cipher 

- app/main/hashers/index.ts
- app/main/hashers/sha256.ts
- app/main/persisters/inMemory.ts
- app/main/persisters/index.ts
- app/main/persisters/level.ts
- test/app/main/hashers/sha256.fixtures.ts
- test/app/main/hashers/sha256.spec.ts
These are modular storage backends to be used as subsystems or as part of other subsystems.
fix #186, fix #187
> feat(subsystems): add Persister, InMemoryPersister and LevelPersister

- app/common/ipc-protocol.ts
fix #207
No business logic to test.
> fix(ipc): make IPC response serializer encode Arrays properly

- app/renderer/ui/app.global.scss
- app/renderer/ui/reset.scss
fix #178
Add css reset to reduce browser inconsistencies.
> feat: feat(css): add css reset to reduce browser inconsistencies

- app/renderer/ui/_colors.scss
- app/renderer/ui/app.global.scss
- app/renderer/ui/components/input/big/style.scss
- app/renderer/ui/components/input/underlined/style.scss
- app/renderer/ui/components/signup/steps/adressesGeneration/style.scss
- app/renderer/ui/components/signup/steps/walletSeedBackup/style.scss
- app/renderer/ui/components/signup/steps/walletSeedConfirmation/style.scss
- app/renderer/ui/components/signup/steps/walletSeedTypeSelection/style.scss
- app/renderer/ui/components/signup/steps/welcome/style.scss
- app/renderer/ui/components/signup/style.scss
re #208
Add ant's css color variables. It provides useful color palettes to use.
> feat: feat(css) add ant's css color variables

- app/renderer/ui/app.global.scss
- app/renderer/ui/fonts.scss
fix #209
Add font size and font line height variables inspired on material's principles. It provides a consistent way to set font sizes.
> feat: feat(css): add font size and font line height variables

- .travis.yml
- app/common/runtimeTypes/storage/wallets.ts
> refactor(walletinfo): rename name field to id

- test/app/main/api/handlers/getWallets.spec.ts
re #229
This PR adds missing tests for the getWallets handler.
> test(handlers): add tests for the getWallets handler

- app/common/runtimeTypes/storage/wallets.ts
> feat(wallets): implement Wallet runtime type

- app/main/crypto/address/p2pkh.ts
- app/main/crypto/key/privateKey.ts
- app/main/crypto/key/publicKey.ts
- app/main/encoding/slip32.ts
- app/main/hashers/sha256Buffer.ts
- app/main/subsystems/jsonPlainLevel.ts
- app/renderer/reducers/wallets.ts
- test/app/main/crypto/address.spec.ts
- test/app/main/crypto/hash.spec.ts
- test/app/main/crypto/key.spec.ts
- test/app/main/crypto/keyFixtures.ts
- test/app/main/crypto/keyPathFixtures.ts
- test/app/main/crypto/keypath.spec.ts
- test/app/main/crypto/pbkdf2.spec.ts
- test/app/main/crypto/seed.spec.ts
- test/app/main/encoding/slip32.spec.ts
fix #247
Replace relative paths by absolute path adding consistency to the project. No test provided because of there are style changes.
> style(paths): replace relative paths by absolute paths

- app/main/subsystems/wallets.ts
- app/main/system.ts
> refactor(subsystems): remove wallet storage collection

- app/main/subsystems/appState.ts
- app/main/subsystems/jsonAesLevel.ts
- app/main/subsystems/jsonPlainLevel.ts
- app/main/system.ts
- app/renderer/ui/pages/main/sections/index.tsx
- config/tsconfig.json
> build(tsconfig): activate strictPropertyInitialization

- app/main/crypto/mnemonic.ts
- app/main/crypto/seed.ts
- test/app/main/crypto/mnemonic.spec.ts
> fix(mnemonic validation): isValid function does not work correctly

- app/main/lifecycle.ts
- app/main/subsystems/appState.ts
- app/main/system.ts
Refactor appStateSubsystem to use pureSubsystem and update wrong config argument type in lifecycle interface.
> refactor(subsystem): appStateSubsystem to use pureSubsystem 

- config/tsconfig.json
- config/tsconfig.test.json
for some reason I don't yet understand IDEs don't look at the
`compilerOptions.typeRoots` property in tsconfig.json
fixes #271
> fix(tsconfig): include @types files

- app/common/config/common.ts
- app/common/config/index.ts
- app/common/runtimeTypes/ipc/wallets.ts
- app/main/api/handlers/index.ts
- app/main/api/handlers/validateMnemonics.ts
- app/main/appState.ts
- test/app/main/api/handlers/validateMnemonics.spec.ts
add a new handler `validateMnemonics` that receives a
`ValidateMnemonicsParam` and returns a `ValidateMnemonicsResponse`.
Closes #222 
> feat(validate mnemonic handler): handler for validating mnemonics

- app/common/runtimeTypes/ipc/wallets.ts
- app/common/runtimeTypes/storage/jsonAesLevel.ts
- app/common/runtimeTypes/storage/wallets.ts
- app/main/api/handlers/getWallet.ts
- app/main/api/handlers/index.ts
- app/main/api/routes.ts
- app/main/storage/jsonAesLevel.ts
- app/main/subsystems/storageFactory.ts
- app/main/subsystems/wallets.ts
- app/main/system.ts
- app/main/utils/utils.ts
Add getWallet handler closing #232.
Test coverage for code added in this PR will be object of separate issues/PRs.
> feat(handlers): unlock wallets

- app/common/runtimeTypes/ipc/wallets.ts
- app/common/runtimeTypes/storage/wallets.ts
- app/main/api/handlers/getWallet.ts
- app/main/api/handlers/newMnemonics.ts
- test/app/main/api/handlers/newMnemonics.spec.ts
- test/app/renderer/api/newMnemonics.spec.ts
Update newMnemonics and getWallet handlers to follow build response and encode it style.
> feat(handlers): Update newMnemonics and getWallet handlers

- app/renderer/routes.tsx
- app/renderer/ui/app.html
- app/renderer/ui/containers/LoginForm.tsx
- app/renderer/ui/pages/main/index.tsx
- app/renderer/utils/redirectedRoute.tsx
The router includes the following routes:
+ `/main` renders `MainPage`
+ `forms/login` renders `LoginFormContainer`
+ `forms/wallet` renders `SignUpPage`
+ `/` redirects to the login or sign-up form depending on the existence of wallet infos in the redux store
PS: some route paths have been hardcoded because they have not yet been exported from their corresponding containers. Nevertheless, they have been tagged with `TODO` comments.
[style]: …
> feat(routes): make topmost router pivot over WalletInfos

- app/common/config/common.ts
- app/common/config/index.ts
- app/common/runtimeTypes/index.ts
- app/common/runtimeTypes/ipc/wallets.ts
- app/common/runtimeTypes/storage/wallets.ts
- app/main/api/handlers/encryptWallet.ts
- app/main/api/handlers/importSeed.ts
- app/main/api/handlers/index.ts
- app/renderer/api/encryptWallet.ts
- test/app/main/api/handlers/encryptWallet.spec.ts
- test/app/main/api/handlers/encryptWalletFixtures.ts
- test/app/main/api/handlers/importSeed.spec.ts
> feat(handlers): make newWallet handler accept xprv seeds

- config/tsconfig.json
> chore(tsconfig): fix outDir to point to <root>/dist

- app/renderer/constants/urls.ts
Fix wallet seed type confirmation route.
> fix(routes): fix wallet seed confirmation route

- app/renderer/ui/components/button/link/style.scss
- app/renderer/ui/components/button/navigation/style.scss
- app/renderer/ui/components/card/default/style.scss
- app/renderer/ui/components/input/big/style.scss
- app/renderer/ui/components/input/underlined/style.scss
- app/renderer/ui/components/loadingModal/style.scss
- app/renderer/ui/components/paymentRequest/style.scss
- app/renderer/ui/components/popover/style.scss
- app/renderer/ui/components/spinner/style.scss
- app/renderer/ui/components/topBar/style.scss
- app/renderer/ui/components/transaction/confirmed/style.scss
- app/renderer/ui/components/transaction/pending/style.scss
- app/renderer/ui/components/wrapper/style.scss
- app/renderer/ui/theme.scss
Add css theme file and move upgradeable component's style to variables
> feat(css-theme): add theme file

- app/renderer/ui/components/walletForm/steps/walletSeedTypeSelection/index.tsx
- app/renderer/ui/containers/WalletForm.tsx
> feat(forms): modify wallet form to offer prefilled wallets 

- app/renderer/api/getWallet.ts
- app/renderer/prefilledWallet.ts
- app/renderer/ui/containers/LoginForm.tsx
- app/renderer/ui/containers/WalletForm.tsx
> feat(forms): modify loginForm getWallet to support prefilled wallets 

- README.md
> chore(readme): update readme with tooling commands

- app/common/runtimeTypes/storage/wallets.ts
- app/renderer/prefilledWallet.ts
> fix(rt-types): change epochs info to intersection type

- app/renderer/ui/components/layout/sidebarLayout/index.tsx
- app/renderer/ui/components/layout/sidebarLayout/style.scss
- app/renderer/ui/components/loginForm/index.tsx
- app/renderer/ui/containers/LoginForm.tsx
fix #302
Collapse sidebar past wallet selection screen.
> feat(ui): collapse sidebar past wallet selection screen

- app/renderer/index.tsx
this is a bit of a hack that will force the rendering of the / route
whenever the app is reloaded (Ctrl+R). ideally we would have a top
component that takes care of this but in the lack of it this solution
is the more cost-effective.
> fix(issue 390): force / rendering whenever the app reloads

- app/renderer/prefilledTransactions.ts
re #401
This PR includes a transaction data collection to be used for the prefilled wallets.
> feat(tx-data): create transaction data collection for prefilled wallet

- app/common/factories/account.ts
- app/common/runtimeTypes/storage/wallets.ts
- app/main/api/handlers/encryptWallet.ts
- app/renderer/prefilledWallet.ts
- test/app/main/api/handlers/encryptWalletFixtures.ts
Keychain and final keys data structure are now tagged unions (external/internal/rad). Only
external final keys may have metadata.
> feat(wallet): augment wallet type to support final keys metadata

- app/renderer/ui/containers/Main.tsx
- app/renderer/ui/containers/WalletForm.tsx
fix #437
Fix show content after create prefilled wallet.
> fix(form-wallet): fix show content after create prefilled wallet

- app/renderer/ui/components/balances/index.tsx
- app/renderer/ui/components/wrapper/style.scss
- app/renderer/ui/theme.scss
Update Listcards to project the standard box shadow  and update alert color.
close #458 
close #465 
> Improve box-shadow of cards and alert color

- app/renderer/ui/components/paymentRequest/style.scss
- app/renderer/ui/components/transaction/confirmed/style.scss
- app/renderer/ui/components/transaction/pending/style.scss
Remove last list item border bottom
> fix(ui): remove last list item border bottom

- app/renderer/ui/components/main/index.tsx
- app/renderer/ui/components/sidebar/index.tsx
- app/renderer/ui/containers/Main.tsx
fix #476 
Show real active wallet name
> fix(ui): show real active wallet name

- app/renderer/ui/components/main/sections/smartContracts/index.tsx
- app/renderer/ui/components/main/sections/smartContracts/style.scss
- app/renderer/ui/components/main/sections/smartContracts/tabs/editor/index.tsx
- app/renderer/ui/components/main/sections/smartContracts/tabs/editor/style.scss
- app/renderer/ui/components/main/sections/smartContracts/tabs/history/index.tsx
- app/renderer/ui/components/main/sections/smartContracts/tabs/history/style.scss
- app/renderer/ui/components/main/sections/smartContracts/tabs/style.scss
- resources/svg/smartContractsEditorBar.svg
- resources/svg/smartContractsEditorComposer.svg
- resources/svg/smartContractsEditorSideContent.svg
fix #454
Implement smart contracts editor tab.
> feat(ui): implement smart contracts editor tab

- app/renderer/ui/app.global.scss
fix #475
Fix app font to be font family.
> fix(ui-font): fix app font to be font family

- app/renderer/ui/app.global.scss
- app/renderer/ui/components/main/sections/wallet/tabs/send/index.tsx
- app/renderer/ui/components/main/sections/wallet/tabs/send/style.scss
- app/renderer/ui/components/popover/index.tsx
- app/renderer/ui/components/select/fees/index.tsx
> Fix(renderer): fix send tab form

- app/renderer/ui/containers/WalletForm.tsx
Improved copy for "Passwords must match" -> the new one is "Passwords do not match, please retype"
fix #371 
> refactor(copy): improve copy for "Passwords must match"

- app/renderer/ui/components/main/sections/wallet/tabs/send/index.tsx
> fix(send): change "payment request" for "pay to"

- app/renderer/ui/components/main/sections/dataRequests/index.tsx
- app/renderer/ui/components/main/sections/dataRequests/style.scss
- app/renderer/ui/components/main/sections/dataRequests/tabs/editor/index.tsx
- app/renderer/ui/components/main/sections/dataRequests/tabs/editor/style.scss
- app/renderer/ui/components/main/sections/dataRequests/tabs/history/index.tsx
- app/renderer/ui/components/main/sections/dataRequests/tabs/history/style.scss
- app/renderer/ui/components/main/sections/dataRequests/tabs/style.scss
This is the same as PR #521 from @mariocao, but including requested changes.
> fix(ui-compo): remove duplicated div grid layout

- app/renderer/ui/components/main/sections/dataRequests/style.scss
- app/renderer/ui/components/main/sections/smartContracts/style.scss
- app/renderer/ui/components/main/style.scss
the bug was introduced in `571d4a225095f905fa9de7399f74651e28abe675` and fixed by restoring the `overflow: scroll` property of `.main` class. additionally made the navigation bars for data-requests and
smart-contracts sections fixed.
Fixes #531 
> fix(issue): #531 sections not scrollable

- app/main/ui.ts
> feat(ui): added limits to window size (width and height)

- app/common/runtimeTypes/wallet/index.ts
Add runtime types to be able to consume wallet api
close #566
> feat(wallet): add wallet api runtime types

- app/renderer/ui/components/input/amount/index.tsx
- app/renderer/ui/components/input/amount/style.scss
- app/renderer/ui/components/main/sections/community/styles.scss
- app/renderer/ui/components/main/sections/dataRequests/tabs/editor/index.tsx
- app/renderer/ui/components/main/sections/dataRequests/tabs/history/index.tsx
- app/renderer/ui/components/main/sections/dataRequests/tabs/history/style.scss
- app/renderer/ui/components/main/sections/marketplace/index.tsx
- app/renderer/ui/components/main/sections/marketplace/style.scss
- app/renderer/ui/components/main/sections/smartContracts/tabs/history/index.tsx
- app/renderer/ui/components/main/sections/smartContracts/tabs/history/style.scss
- app/renderer/ui/components/main/sections/wallet/tabs/receive/index.tsx
- app/renderer/ui/components/main/sections/wallet/tabs/receive/style.scss
- app/renderer/ui/components/main/sections/wallet/tabs/send/index.tsx
- app/renderer/ui/components/main/sections/wallet/tabs/send/style.scss
- app/renderer/ui/components/main/sections/wallet/tabs/transactions/index.tsx
- app/renderer/ui/components/main/sections/wallet/tabs/transactions/style.scss
- app/renderer/ui/components/main/style.scss
- app/renderer/ui/components/paymentRequest/style.scss
- app/renderer/ui/components/sidebar/index.tsx
- app/renderer/ui/components/sidebar/sidebarLink.tsx
- app/renderer/ui/components/sidebar/style.scss
- app/renderer/ui/components/topBar/style.scss
close #564 close #537 
close #542 close #562 
> Sidebar collapse animation and CSS form fixes

- .eslintrc
- app/main/api/handlers/getWallet.ts
- app/main/api/handlers/importSeed.ts
- app/renderer/radon/index.ts
- app/renderer/ui/components/radonOperator/index.tsx
- app/renderer/ui/components/radonOperator/style.scss
- app/renderer/ui/components/select/default/index.tsx
- app/renderer/ui/components/select/index.tsx
- app/renderer/utils/objectValues.ts
- stories/RadonOperator.stories.tsx
> feat(ui-compo): implement radon operator component

- app/common/runtimeTypes/wallet/index.ts
- app/renderer/ui/components/main/sections/marketplace/index.tsx
- app/renderer/ui/components/query/index.tsx
- app/renderer/ui/components/query/radonQuery/index.tsx
- app/renderer/ui/components/query/radonQuery/style.scss
- stories/Query.stories.tsx
RadonQuery Component is a part of the new Data Request Editor
> RadonQuery UI Component

- .github/CONTRIBUTING.md
- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- docs/STYLEGUIDE.md
- package.json
This PR updates the documentation removing content about old features and adding those that are news
> docs: fix documentation according the new boilerplate

- src/components/BaseCard.vue
- src/components/Button.vue
- src/components/NavigationCard.vue
- src/stories/index.stories.js
> feat(ui-compo): card component migration

- src/components/TopBar.vue
- src/components/Wallet.vue
- src/router.js
In this PR I migrated the topBar component and also added redirect to the wallet component when the user starts Sheikah so you can see the top bar.
> feat(ui-compo): migrate topBar component + fix redirect error

- package.json
- src/api.js
- src/components/Community.vue
- src/components/DataRequest.vue
- src/components/Editor.vue
- src/components/RadonOperator.vue
- src/components/RadonQuery.vue
- src/components/RadonScript.vue
- src/components/Templates.vue
- src/components/Transaction.vue
- src/radon/index.js
- src/radon/utils.js
- src/router.js
- src/store.js
- src/utils.js
- tests/unit/src/components/RadonOperator.spec.js
- yarn.lock
This PR contains:
- Implementation of the radon components: RadonQuery, RadonScript and RadonOperator.
- Tests for radonOperator covering arrayCount, arrayEvery and arrayReduce methods.
- Add wallet API methods.
- Implementation of the try data request method.
> Implement radon components

- package.json
Update and add package.json fields: _name_, _description_, _author_, _repository_ and _bugs_
> chore(package): update package json information

- src/api.js
- src/components/BaseCard.vue
- src/components/Button.vue
- src/components/Input.vue
- src/components/NavigationCard.vue
- src/components/Sidebar.vue
- src/components/Spinner.vue
- src/components/WelcomeBack/UnlockWallet.vue
- src/components/WelcomeBack/WalletList.vue
- src/components/steps/Loading.vue
- src/components/steps/WalletCreation.vue
- src/components/steps/WalletDisclaimer.vue
- src/components/steps/WalletEncryptionPassword.vue
- src/components/steps/WalletSeedBackup.vue
- src/components/steps/WalletSeedTypeSelection.vue
- src/components/steps/WalletSeedValidation.vue
- src/components/steps/WelcomeForm.vue
- src/main.js
- src/router.js
- src/store.js
- src/views/FirstTimeUsage.vue
- src/views/WelcomeBack.vue
> Implement ftu and welcome back flow

- src/components/Input.vue
- src/components/steps/WalletEncryptionPassword.vue
- src/components/steps/WalletSeedValidation.vue
- src/stories/input.stories.js
This PR contains the implementation of the input component that can be _big_, _underlined_ and default type.
Close #623
> feat(ui-compo): add input component

- src/components/Transaction.vue
- src/components/TransactionList.vue
- src/components/Transactions.vue
- src/components/Wallet.vue
- src/main.js
- src/router.js
> feat(ui-compo): add transaction component

- src/components/Balances.vue
- src/components/Send.vue
- src/components/TransactionList.vue
- src/components/Transactions.vue
- src/store/wallet.js
- src/stories/balances.stories.js
> feat(ui-compo): add balances component

- src/components/Balances.vue
- src/store/wallet.js
Includes a conditional rendering of balances regarding the state
> Implement balances empty state

- .eslintrc.js
- src/background.js
- src/components/Input.vue
- src/components/InputNumber.vue
- src/components/RadonOperator.vue
- src/components/RadonQuery.vue
- src/components/Receive.vue
- src/fontAwesome.js
- src/main.js
- src/radon/utils.js
- src/store/rad.js
- src/views/WelcomeBack.vue
- [] My code is formatted and is accepted by `yarn lint`.
> refactor: move fontAwesome config to separate file

- src/components/Receive.vue
- src/components/Send.vue
Form buttons are aligned and the box in adjusted.
close #728
> fix(style): submit buttons alignment

- src/components/Transaction.vue
- src/components/TransactionList.vue
- src/components/Transactions.vue
- src/resources/svg/empty.svg
Empty transactions list icon added
close #725
> Add empty transactions list icon

- src/api.js
- src/components/Settings.vue
- src/components/Sidebar.vue
- src/components/Transactions.vue
- src/components/WelcomeBack/UnlockWallet.vue
- src/router.js
- src/store/wallet.js
A dropdown option for the "closing session" feature is added.
close #737
> feat: add settings dropdown option for close session

- src/components/Receive.vue
- src/components/Send.vue
- src/components/Transactions.vue
- Fix missing dependency
- Fix Button pointer property
> Fix minor bugs

- src/components/NetworkStatus.vue
- src/components/Settings.vue
- src/components/Sidebar.vue
> Fix sidebar style bugs

- src/components/WelcomeBack/UnlockWallet.vue
Some styles were added to the view.
close #715
> feat(styles): implement view of unlock wallet

- .eslintrc.js
- src/api.js
- src/components/Balances.vue
- src/components/Receive.vue
- src/components/Select.vue
- src/components/Send.vue
- src/components/Settings.vue
- src/components/Sidebar.vue
- src/components/Transaction.vue
- src/components/TransactionList.vue
- src/components/WelcomeBack/UnlockWallet.vue
- src/components/card/Card.vue
- src/components/steps/Loading.vue
- src/store/wallet.js
- src/views/WelcomeBack.vue
This PR implements transaction creation and confirmation throughout a confirmation view
> Implement create transaction flow

- src/store/wallet.js
Connect the generate address form with the new wallet api
> feat(api): connect generate address with wallet

- config/storybook/config.js
Add font-awesome configuration to storybook
> fix(storybook): use fontawesome icons in stories

- src/components/card/CommunityCard.vue
> feat(ui-compo): implement community view

- src/components/Templates.vue
> fix: change description text

- src/components/Carousel.vue
- src/components/Templates.vue
Create slide animation for Carousel
> feat(style): Implement animation for Carousel component

- package.json
- src/api.js
- src/components/Carousel.vue
- src/components/Editor.vue
- src/components/RadonStage.vue
- src/components/StageBar.vue
- src/components/Templates.vue
- src/components/ToolBar.vue
- src/components/card/TemplateCard.vue
- src/store/rad.js
- src/utils.js
This PR implements:
- export template from fs
- import templates from fs
- step back and forward in the editor
- save, modify and delete template through vuex
> feat(toolbar): implement editor toolbar methods

- src/components/Carousel.vue
- src/components/Editor.vue
- src/components/RadonStage.vue
- src/radon/index.js
- src/radon/structures.js
- src/store/rad.js
This PR contains:
- Delete radon operators below the updated one if the script is not valid anymore.
- Implement `updateSource` method in radon interpreter
- Implement `deleteSource` method in radon interpreter
> Improve radon interpreter library

- src/components/Carousel.vue
- src/components/Editor.vue
- src/components/Wallet.vue
- src/radon/index.js
- src/store/rad.js
- src/store/wallet.js
- src/stories/radon.stories.js
- src/utils.js
- yarn.lock
Connect try data request method to the wallet and show errors. 
close #804
> feat: connect try data request method to wallet

- src/components/Editor.vue
- src/components/ToolBar.vue
- src/radon/index.js
- src/store/rad.js
fix save template in data request Editor.
> fix: save template

- src/components/Carousel.vue
- src/store/rad.js
> Fix undo redo

- src/components/Alert.vue
- src/components/Receive.vue
- src/components/Transactions.vue
- src/store/wallet.js
- tests/unit/transactions.spec.js
Unit test for ListAddresses component.
> List addresses test

- src/api.js
- src/components/Send.vue
- src/components/Transactions.vue
- src/store/wallet.js
The default Timelock value has been added and the Confirm Transaction component modal has been fixed.
> Default timelock

- package.json
- src/components/Editor.vue
- src/components/RadonScript.vue
- src/components/card/TemplateCard.vue
- src/store/rad.js
- yarn.lock
This PR includes the integration of the new radon library
close #816
> feat(radon): integrate radon lib

- src/components/Receive.vue
- src/components/Send.vue
- src/components/Transactions.vue
Fix send and receive transactions component.
> Fix send and receive transactions component

- src/components/Editor.vue
- src/components/Input.vue
- src/components/RadonOperator.vue
- src/components/RadonStage.vue
- src/components/Variables.vue
- src/components/card/TemplateCard.vue
- src/directives.js
- src/store/rad.js
- src/store/wallet.js
This PR adds a variables list component that can be edited and stored to reference them in the data request editor.
> Add variables to template

- src/components/Select.vue
This PR fixes some small style issues in send transaction component.
> fix(styles): select in send transaction component

- src/components/Console.vue
- src/components/ConsoleTab.vue
- src/components/Editor.vue
- src/components/Logs.vue
- src/components/Sidebar.vue
- src/components/Variables.vue
- src/styles/_colors.scss
- tests/unit/consoleTab.spec.js
This PR includes the implementation of a console component which includes a tab-bar for editing variables and showing logs. 
It also adds a unit test for the tab-bar component.
> Implement console component and tab-bar for console component

- src/components/Carousel.vue
- src/components/EditableText.vue
- src/components/Editor.vue
- src/components/Input.vue
- src/components/RadonOperator.vue
- src/components/Send.vue
- src/components/Templates.vue
- src/components/Variables.vue
- src/components/card/TemplateCard.vue
- src/fontAwesome.js
- src/store/rad.js
- src/store/wallet.js
- src/utils.js
Implements component for editing texts
> Implement component for editing texts

- src/components/Alert.vue
- src/components/Carousel.vue
- src/components/Community.vue
- src/components/ConsoleTabs.vue
- src/components/EditableText.vue
- src/components/Input.vue
- src/components/InputNumber.vue
- src/components/ListAddresses.vue
- src/components/NetworkStatus.vue
- src/components/PasswordInput.vue
- src/components/RadonOperator.vue
- src/components/Receive.vue
- src/components/Select.vue
- src/components/Send.vue
- src/components/Settings.vue
- src/components/Sidebar.vue
- src/components/Templates.vue
- src/components/Transactions.vue
- src/components/Variables.vue
- src/components/WelcomeBack/UnlockWallet.vue
- src/components/WelcomeBack/WalletList.vue
- src/components/card/CommunityCard.vue
- src/components/card/InformativeContent.vue
- src/components/card/NavigationCard.vue
- src/components/card/TemplateCard.vue
- src/components/steps/Loading.vue
- src/components/steps/WalletEncryptionPassword.vue
- src/components/steps/WalletSeedTypeSelection.vue
- src/components/steps/WelcomeForm.vue
- src/views/WelcomeBack.vue
This PR polish some Sheikah styles.
> Polish CSS

- src/components/WelcomeBack/UnlockWallet.vue
This PR adds a button to go back to the wallets list.
> Implement button to go back to wallets list

- src/components/ConsoleTabs.vue
- src/store/rad.js
This PR integrates the new radon library with undo-redo methods in Editor.
> fix(undo-redo): new radon library integration with undo-redo

- package.json
- src/components/RadonOperator.vue
- yarn.lock
- Fix update operator call in Editor component
- upgrade witnet-radon-js version
> fix(radon): update operators call

- src/components/Settings.vue
- src/components/Sidebar.vue
- src/views/WelcomeBack.vue
This Pr fixes the settings component and adds it to the welcome-back flow.
> fix(ui-compo): update settings component

- package.json
- src/App.vue
- src/api.js
- src/components/Marketplace.vue
- src/store/index.js
- src/store/marketplace.js
- yarn.lock
This PR includes a naive integration between Sheikah and the marketplace-api
> consume marketplace api

- package.json
- src/components/RadonAggregateTallyScript.vue
- src/components/RadonOperator.vue
- src/components/RadonScript.vue
- src/components/RadonStage.vue
- src/components/Select.vue
- src/store/rad.js
- yarn.lock
Implement new radon stages according to  witnet/witnet-rust#912
> Implement new radon stages

- src/components/Transaction.vue
- src/components/Transactions.vue
- src/store/wallet.js
This PR update the method to send VTTs.
> fix: send transaction method to match wallet params

- src/components/PasswordInput.vue
- src/components/WalletNotFound.vue
- src/components/WelcomeBack/UnlockWallet.vue
- src/main.js
- src/router.js
This PR implements the error message when the password is not valid and a warning message when running Sheikah the Wallet is not synced.
> Show errors and warnings

- src/components/ListAddresses.vue
- src/components/NetworkStatus.vue
This PR makes the pagination logic more readable.
> Refactor pagination

- src/components/Editor.vue
- src/components/RadonStage.vue
- src/components/Templates.vue
- src/components/Transactions.vue
- src/components/Wallet.vue
- src/components/WelcomeBack/UnlockWallet.vue
- src/components/steps/Loading.vue
- src/components/steps/WalletDisclaimer.vue
- src/components/steps/WalletEncryptionPassword.vue
- src/components/steps/WalletSeedBackup.vue
- src/components/steps/WalletSeedValidation.vue
- src/store/rad.js
- src/store/wallet.js
- src/views/Home.vue
This PR unifies the way to handle errors covering all wallet calls.
> Handle wallet errors

- TemplateExample.json
- src/store/rad.js
- Fix import template according to the new radon version
> Fix import template

- src/components/Send.vue
- src/components/Transaction.vue
- src/components/TransactionList.vue
- src/components/Transactions.vue
- src/store/wallet.js
- src/utils.js
- tests/e2e/specs/test.js
This PR save transaction labels and show it in the transaction component.
> Save transactions labels

- TemplateExample.json
- package.json
- src/components/Console.vue
- src/components/Editor.vue
- src/components/Logs.vue
- src/components/card/TemplateCard.vue
- src/store/rad.js
- src/store/wallet.js
- src/utils.js
- yarn.lock
- Implement try data request
- Show the result in the editor console
> Implement try data request

- src/api.js
- src/components/Balances.vue
- src/components/Transactions.vue
- src/store/wallet.js
- src/views/Home.vue
We should make sure that subscriptions to new transactions that relate to a particular wallet do work.
Close #883
> Tx subscription

- package.json
- src/components/Carousel.vue
- src/components/RadonOperator.vue
- src/components/RadonScript.vue
- src/components/Select.vue
- src/components/Send.vue
- src/store/rad.js
- src/utils.js
- tests/e2e/utils.js
- yarn.lock
> Improve editor usability

- src/components/Alert.vue
- src/components/DeployDataRequest.vue
- src/components/Editor.vue
- src/components/Send.vue
- src/components/Templates.vue
- src/components/Transactions.vue
- src/components/Wallet.vue
- src/router.js
- src/store/wallet.js
- src/utils.js
- src/views/FirstTimeUsage.vue
- src/views/Home.vue
- src/views/WelcomeBack.vue
This pr fixed redirections to alert when the wallet or the node is not synced
> fix: alert redirection when the wallet or the node is not synced

- src/components/Carousel.vue
- src/components/RadonOperator.vue
- src/components/Select.vue
- src/components/Variables.vue
- src/utils.js
- tests/e2e/utils.js
- tests/unit/standarizeOperatorName.spec.js
This PR creates a method to standardize operator names in select and fixes style.
> Fix select operator

- package.json
- src/components/Carousel.vue
- src/components/RadonScript.vue
- src/store/rad.js
Allow use empty radon scripts.
> feat(editor): allow use empty scripts in editor

- tests/e2e/specs/accessView.js
- tests/e2e/support/commands.js
- tests/e2e/utils.js
- Remove anti-pattern way to create a wallet with cypress
- Add access vuex command in cypress
- Add create wallet command in cypress
> test(e2e): add vuex and create wallet cypress commands

- src/components/Carousel.vue
- src/components/EditableText.vue
- src/components/Editor.vue
- src/components/PasswordInput.vue
- src/components/RadonOperator.vue
- src/components/RadonScript.vue
- src/components/Select.vue
- src/components/Templates.vue
- src/components/ToolBar.vue
- src/components/Variables.vue
- src/components/card/TemplateCard.vue
- src/components/steps/WelcomeForm.vue
- src/utils.js
- tests/e2e/specs/createDr.js
This PR adds an e2e for creat and edit a template.
> e2e test for create and edit template

- src/components/CompleteVariablesForm.vue
- src/components/ConfirmDataRequest.vue
- src/components/CreateDataRequestForm.vue
- src/components/Editor.vue
- src/components/Templates.vue
- src/components/card/TemplateCard.vue
- src/views/FirstTimeUsage.vue
- tests/e2e/specs/createDr.js
- tests/e2e/specs/deployDR.js
This PR adds e2e tests for deploying data requests.
> e2e tests for deploying data requests

- src/components/Balances.vue
- src/components/Transaction.vue
- src/components/TransactionList.vue
- src/components/Transactions.vue
- src/constants.js
- src/store/wallet.js
- src/utils.js
- tests/unit/src/utils.spec.js
This PR adds a method to standardize currency unit in balances and transactions.
> Add standardize method to set currency unit

- package.json
- src/components/RadonOperator.vue
- src/utils.js
- tests/e2e/specs/createDr.js
- yarn.lock
Update with radon inputs with the correct type
> fix(editor): update argument with correct type

- .travis.yml
- src/components/CompleteVariablesForm.vue
- src/components/ConfirmDataRequest.vue
- src/components/CreateDataRequestForm.vue
- src/components/DeployDataRequest.vue
- src/components/Modal.vue
- src/components/Templates.vue
- src/components/WelcomeBack/UnlockWallet.vue
- src/store/rad.js
- src/store/wallet.js
- src/utils.js
- tests/e2e/specs/createDr.js
- tests/e2e/specs/deployDR.js
Implement deploy data request flow
> Deploy data request

- src/router.js
- src/store/wallet.js
This PR adds redirection to the wallet list when the user is not authorized anymore.
> Redirect when un-authorized user

- src/components/Carousel.vue
- src/components/RadonAggregateTallyScript.vue
- src/components/RadonOperator.vue
- src/components/Transaction.vue
- src/store/wallet.js
- src/utils.js
- tests/e2e/specs/createDr.js
- Replace custom select by element-ui select
- Remove address from transaction component
- Update date in transaction component
- Show the error received from the wallet in deploy data request flow
> ref(ui-compo): update custom select by element select

- src/components/Carousel.vue
- src/components/ConsoleTabs.vue
- src/components/Editor.vue
- src/components/Logs.vue
- src/components/Sidebar.vue
- src/components/ToolBar.vue
- src/views/Home.vue
This PR fixed the console position and style.
> fix: console position and style

- ci/genesis_block.json
- ci/witnet.toml
- src/App.vue
- src/api.js
- src/components/Select.vue
- src/store/rad.js
- src/store/wallet.js
This PR updates to snake_case all the names in the wallet API calls.
> Rename wallet methods

- src/components/Carousel.vue
- src/components/CompleteVariablesForm.vue
- src/components/ConfirmDataRequest.vue
- src/components/CreateDataRequestForm.vue
- src/components/DeployDataRequest.vue
- src/components/RadonOperator.vue
- src/components/Receive.vue
- src/components/Send.vue
- src/components/Templates.vue
- src/components/Transactions.vue
Add element-ui components and validations to these flows:
> Replace custom components by element-ui ones

- src/components/Sidebar.vue
- src/components/Templates.vue
- src/components/Transactions.vue
- src/components/card/TemplateCard.vue
- src/router.js
- yarn.lock
This PR adds an animation when hovering sidebar and fixes send and receive tx button position.
> Animation in side bar + send/receive tx button position

- src/components/ListAddresses.vue
- src/components/Marketplace.vue
- src/components/Templates.vue
- src/components/TransactionList.vue
- src/components/Transactions.vue
- src/store/wallet.js
- src/styles/element-variables.scss
- tests/e2e/specs/deployDR.js
- tests/unit/transactions.spec.js
This PR changes pagination to element UI component and paginate templates and transactions.
> Paginate transactions and templates

- src/components/NetworkStatus.vue
- src/components/Sidebar.vue
- src/components/Templates.vue
- src/components/card/Card.vue
- src/components/steps/WalletEncryptionPassword.vue
- src/components/steps/WalletImport.vue
- src/components/steps/WalletSeedTypeSelection.vue
- src/router.js
- src/store/wallet.js
- src/views/Home.vue
This PR implements the flow for importing a wallet except for the seed validation.
> Import wallet flow

- src/components/claiming/DownloadFile.vue
- src/components/claiming/GenerateAddresses.vue
- src/constants.js
- src/router.js
- src/store/wallet.js
Implement generate addresses step
> Generate addresses

- src/components/claiming/UploadFile.vue
This PR handle preview on click uploaded file to download it.
> Handle preview on click uploaded file

- src/App.vue
- src/components/claiming/Loading.vue
- src/components/steps/Loading.vue
This PR fixes the UI in ```Loading.vue``` component to not overlap.
> Fix loading

- src/components/claiming/UploadFile.vue
- src/components/claiming/WalletEncryptionPassword.vue
- src/components/claiming/WalletSeedValidation.vue
- src/router.js
- src/store/wallet.js
Show error when no claiming file is uploaded as a validation error.
> Fix error when no claiming file is uploaded

- src/components/claiming/UploadFile.vue
Allow replace imported file in claiming process
close #985
> Remove import claiming file limit

- src/components/card/NavigationCard.vue
- src/components/claiming/DownloadFile.vue
- src/components/claiming/FileInformation.vue
- src/components/claiming/GenerateAddresses.vue
- src/components/claiming/Instructions.vue
- src/components/claiming/UploadFile.vue
- src/components/claiming/WalletDisclaimer.vue
- src/components/claiming/WalletEncryptionPassword.vue
- src/components/claiming/WalletSeedBackup.vue
- src/components/claiming/WalletSeedValidation.vue
- src/styles/_colors.scss
- src/styles/element-variables.scss
- src/styles/theme.scss
- src/views/ClaimingProcess.vue
This PR fixes the UI in the claiming process flow.
> Fix ui in claiming process flow

- src/components/claiming/DownloadFile.vue
- src/store/wallet.js
- src/utils.js
Allow export the claiming file at the end of the claiming process
Close #994
> Export claiming file

- claiming-file.json
- src/components/claiming/GenerateAddresses.vue
- src/components/claiming/Loading.vue
- src/components/claiming/UploadFile.vue
- src/store/wallet.js
- src/utils.js
This PR validates the claiming file uploaded.
> Validate claiming file

- src/components/claiming/DownloadFile.vue
- src/components/claiming/UnlockWallet.vue
- src/router.js
- src/store/wallet.js
- src/utils.js
This PR redirects the user to unlock the wallet when the claiming process is completed.
> Redirect to unlock wallet when claiming process completed

- src/api.js
- src/components/claiming/Loading.vue
- src/router.js
- src/store/wallet.js
This PR create disclaimers and signs them using the ```sign_data``` method provided by the wallet.
> Sign disclaimers

- src/components/ListAddresses.vue
- src/components/WelcomeBack/UnlockWallet.vue
- src/components/card/BaseCard.vue
- src/components/card/Card.vue
- src/components/card/Disclaimer.vue
- src/components/card/InformativeContent.vue
- src/components/card/NavigationCard.vue
- src/components/claiming/ClaimingInfo.vue
- src/components/claiming/Countdown.vue
- src/components/claiming/DownloadFile.vue
- src/components/claiming/UnlockWallet.vue
- src/components/claiming/Vesting.vue
- src/components/claiming/WalletDisclaimer.vue
- src/components/claiming/WalletEncryptionPassword.vue
- src/components/steps/WalletEncryptionPassword.vue
- src/components/steps/WalletSeedTypeSelection.vue
- src/components/steps/WelcomeForm.vue
- src/fontAwesome.js
- src/router.js
- src/store/wallet.js
- src/styles/_colors.scss
- src/styles/element-variables.scss
- src/styles/theme.scss
- src/utils.js
- src/views/FirstTimeUsage.vue
- src/views/WelcomeBack.vue
- tests/e2e/specs/claimingProcess.js
-  Implement disclaimer component
-  Update theme colors and default shadow
-  Change password input
-  Update DownloadFile component to the new style
-  Update Centered Layout to be able to show a message below the main card
-  Update Card to be able to add a footer without padding
-  Implement vesting table
> Update Sheikah theme to fit new style

- src/background.js
Disable reload from keyboard shortcut
> feat: disable relaod from cmdOrCtrl+r

- examples/data_request1.json
- examples/data_request2.json
- examples/data_request3.json
Create example folder and add data requests that can be used to import in sheikah
> docs: add dr examples to import

- src/components/Carousel.vue
Fix a bug that doesn't allow the user write in the source input
> fix(editor): allow write in source input

- src/components/FileUploader.vue
- src/components/claiming/Countdown.vue
- src/components/claiming/UploadFile.vue
- src/fontAwesome.js
- src/router.js
- src/store/wallet.js
- src/styles/theme.scss
- styleguide.config.js
- styleguide/scripts.js
- tests/e2e/specs/claimingProcess.js
- tests/unit/src/components/FileUploader.spec.js
This PR implements a ```FileUploader``` component + tests.
> Implement drag and drop 

- .travis.yml
> chore: update travis file to run on master

- src/router.js
This PR fixes router redirection so there is no need to delete local storage to make it work on development.
> fix: router redirection

- src/components/AddressInformation.vue
- src/components/Addresses.vue
- src/components/Amount.vue
- src/components/InputsOutputs.vue
- src/components/Send.vue
- src/components/Transaction.vue
- src/utils.js
- tests/unit/src/components/AddressInformation.spec.js
- tests/unit/src/components/Addresses.spec.js
- tests/unit/src/components/Amount.spec.js
- tests/unit/src/components/InputsOutputs.spec.js
- tests/unit/src/components/Transaction.spec.js
Validate available funds before create a value transfer transaction
Close #1072
> feat: validate funds before create vtt

- src/components/NetworkStatus.vue
- src/utils.js
This PR fixes change the date format when the timestamp is 10 digit.
> fix: change date format

- src/components/Input.vue
- src/components/resizeMixin.js
- src/components/steps/WalletImport.vue
- src/components/steps/WalletSeedValidation.vue
- tests/e2e/specs/createWallet.js
> fix: remove textarea behaviour from mnemonics input

- src/components/DeployDataRequest.vue
- src/components/Editor.vue
- src/components/NetworkStatus.vue
- src/components/Send.vue
- src/components/Templates.vue
- src/components/Wallet.vue
- src/components/steps/WalletSeedBackup.vue
- src/store/rad.js
- src/utils.js
- tests/unit/src/components/NetworkStatus.spec.js
This PR deletes no needed alerts and uses `date-fns` to format timestamps.
> Delete alerts when no needed and fix date format.

- src/components/NetworkStatus.vue
- src/components/WelcomeBack/WalletList.vue
- src/store/wallet.js
- tests/unit/src/components/NetworkStatus.spec.js
This PR save last wallet used to keep it selected in the unlock wallet view.
> Select last wallet used

- src/components/WelcomeBack/WalletList.vue
- src/components/card/Disclaimer.vue
- src/components/card/NavigationCard.vue
- src/components/steps/Loading.vue
- src/components/steps/WalletEncryptionPassword.vue
- src/directives.js
This PR creates a directive to focus element and use it in unlock wallet and create wallet flow.
> Create directive to focus element

- src/components/card/Disclaimer.vue
- src/components/card/NavigationCard.vue
- src/components/claiming/Vesting.vue
- src/components/claiming/WalletEncryptionPassword.vue
- src/components/steps/WalletEncryptionPassword.vue
- src/directives.js
- yarn.lock
This PR improves accessibility in the claiming process.
> Improve accessibility in claiming process

- src/components/AddressInformation.vue
- src/components/AddressList.vue
- src/components/Tag.vue
- src/store/wallet.js
- src/styles/_colors.scss
This PR unifies colors with Sheikah palette.
> Unify colors with Sheikah palette

- src/components/RenameTemplate.vue
- src/components/Templates.vue
- src/components/card/TemplateCard.vue
- src/store/rad.js
- src/utils.js
- tests/e2e/specs/deployDR.js
This PR creates a modal for renaming templates and change the template description.
> Create modal for renaming templates

- src/components/InputsOutputs.vue
- src/components/Send.vue
- src/components/steps/WalletImport.vue
- src/store/wallet.js
This PR adds a notification when a transaction is sent successfully
> Add notification when a transaction is sent successfully

- src/components/RadonStage.vue
- src/components/StageBar.vue
- styleguide.config.js
- tests/e2e/specs/createDr.js
- tests/unit/src/components/StageBar.spec.js
This PR implements a new stage bar to match new style in the editor view
> Implement new stage bar

- src/App.vue
- src/background.js
This PR disables zooming with pitch and suggests a way to disable zoom hotkeys, although it is not convenient.
> Disable zoom with pitch

- src/components/OperatorOutput.vue
- src/components/OperatorType.vue
- src/components/RadonOperator.vue
- src/components/RadonScript.vue
- src/resources/svg/close-btn.svg
- src/resources/svg/delete-btn.svg
- src/styles/theme.scss
- src/utils.js
This pr implements a delete operator button and allows adding operators when the script is empty.
> Implement delete operator and fix add operator when empty script

- package.json
- src/components/EditorStageScripts.vue
- src/components/RadonScript.vue
- src/components/ScriptInfo.vue
- src/components/card/EditorScript.vue
- tests/unit/src/components/ScriptInfo.spec.js
- yarn.lock
This PR implements a script info component to be added to the ```RadonScript.vue```.
> Implement script info component

- src/components/EditableText.vue
- src/components/EditorSettings.vue
- src/components/EditorStageSettings.vue
- src/components/RadonOperator.vue
- src/components/RadonScript.vue
- src/components/RenameTemplate.vue
- src/components/ScriptInfo.vue
- src/components/Select.vue
- src/components/Variables.vue
- src/resources/svg/close-btn.svg
- src/store/rad.js
- src/styles/element-variables.scss
- tests/unit/src/components/RenameTemplate.spec.js
- tests/unit/src/components/ScriptInfo.spec.js
- tests/unit/src/components/Variables.spec.js
This PR adds the form to rename the template and create variables to the settings stage. It also adds a description and a data type fields to the variables component.
> Settings stage in Editor

- src/components/AddressInformation.vue
- src/store/wallet.js
Change addresses order and set default address to 1
> Fix address listing

- src/components/Send.vue
Remove Send Modal component `width: 100%`
> fix(send): remove wrong width

- src/api.js
- src/store/wallet.js
- src/views/Transactions.vue
Upate periodically the transaction details copy: `{{ nnnnn }} {{ time }}  ago`
Close #1148
> Update date in transactions periodically

- src/components/Variables.vue
This pr fixes the position of the delete variable button
> Fix delete variable button position

- src/components/Console.vue
Delete the variables tab in the console.
> Delete variables tab in console

- src/utils.js
- tests/unit/src/utils.spec.js
- Update copy to contain ago copy
- Set minimum time unit in minutes
> fix(timeAgo): update copy to contain ago word

- src/components/Variables.vue
This pr fixes the update of the keys in variables
> Update key in variables

- src/components/CompleteVariablesForm.vue
- src/components/ConfirmDataRequest.vue
- src/components/CreateDataRequestForm.vue
- src/components/DeployDataRequest.vue
- src/components/Editor.vue
- src/components/EditorToolBar.vue
- src/store/wallet.js
- tests/e2e/specs/deployDR.js
- tests/unit/src/components/EditorToolbar.spec.js
Add deploy data request to the toolbar in the Editor component and fix small CSS issues.
> Add deploy data request to toolbar

- src/background.js
> Add Sheikah to the system tray

- src/store/rad.js
- src/utils.js
> Fix try data request

- src/background.js
> feat(window): set min and max width and height

- src/components/AddressList.vue
- src/components/Send.vue
- src/resources/svg/close.svg
- src/resources/svg/open.svg
- src/styles/element-variables.scss
- src/styles/scroll.scss
> Fix style in send transaction

- src/components/ConfirmDataRequest.vue
- src/components/CreateDataRequestForm.vue
- src/components/DeployDataRequest.vue
- src/store/wallet.js
Removes backup factor and extra rounds in transactions
Close #1122
> Removes backup factor and extra rounds

- src/api.js
- src/components/Transaction.vue
- src/components/TransactionDetails.vue
- src/components/WalletNotFound.vue
- src/utils.js
- tests/unit/src/components/Transaction.spec.js
Shows transactions details in the tally transaction
> Transaction details in tally transaction

- src/components/WelcomeBack/WalletList.vue
- src/components/steps/WalletSeedTypeSelection.vue
Fixes update of current wallet in wallet list select and removes import from xprv.
> Remove import from xprv

- src/background.js
> feat: open urls in browser instead of electron window

- src/components/Sidebar.vue
- tests/e2e/specs/accessView.js
> feat: hide marketplace section until is ready

- src/components/OperatorOutput.vue
Show output if it fits in the output box
> Show output if it fits in the output box

- src/components/OperatorOutput.vue
> feat(editor): add string as explicit output

- src/components/DotsLoading.vue
- src/components/EditorStageSources.vue
- src/components/EditorToolBar.vue
- src/components/OperatorOutput.vue
- src/components/RadonAggregateTallyScript.vue
- src/components/RadonOperator.vue
- src/components/RadonScript.vue
- src/components/card/TemplateCard.vue
- src/store/rad.js
- src/store/uiInteractions.js
- src/store/wallet.js
- tests/unit/src/components/EditorStageSources.spec.js
- tests/unit/src/components/EditorToolbar.spec.js
- tests/unit/src/components/OperatorOutput.spec.js
- tests/unit/src/components/RadonAggregateTallyScript.spec.js
- tests/unit/src/components/RadonOperator.spec.js
Try the data request automatically when it is updated and add a loader.
close #1198
> Try data request when the request is updated

- src/store/wallet.js
- src/utils.js
> fix: set correct synced status on wallet event

- .travis.yml
- ci/initializeWallet.sh
- ci/initializeWitnet.sh
- src/components/AddressCardButton.vue
- src/components/AddressInformation.vue
- src/components/EditorSource.vue
- src/components/EditorStageSources.vue
- src/components/EditorToolBar.vue
- src/components/RadonOperator.vue
- src/components/Sidebar.vue
- src/components/Variables.vue
- src/components/card/Card.vue
It Adds tooltips when necessary and fixes the title tooltip in the source card.
close #1201
> Add tooltips when necessary

- src/background.js
- src/components/RadonAggregateTallyScript.vue
- src/components/RadonScript.vue
Add output to first returned result in the aggregator, retrieve, and tally stages.
close #1197
> Add output to first returned result

- src/components/RadonOperator.vue
- src/utils.js
It Fixes the error result message that is shown in partial results to be more readable. 
close #1200
> Fix error result messages

- src/components/EditorSource.vue
- src/components/EditorStageSources.vue
- src/components/Select.vue
Remove protocol and content type options.
close #1196
> Disable protocol and content type options

- src/store/wallet.js
Redirect to wallet list when the session has expired.
close #1194
> Redirect to wallet list when the session has expired

- src/components/AddressCardButton.vue
- src/components/AddressInformation.vue
- src/components/EditorSource.vue
- src/components/EditorToolBar.vue
- src/components/ScriptInfo.vue
- src/components/Variables.vue
This PR fixes the tooltips so that the comment appears in the corresponding button.
close #1220
> Fix tooltip

- src/components/EditorToolBar.vue
- src/components/card/TemplateCard.vue
- src/constants.js
- src/styles/element-variables.scss
- tests/unit/src/components/EditorToolbar.spec.js
- yarn.lock
- Add droppable component for `Export as`.
- Add export as `js` file feature. 
close #1222
> Implement export as javascript file feature

- examples/subscript.json
- package.json
- src/components/EditorOperatorArgument.vue
- src/components/RadonAggregateTallyScript.vue
- src/components/RadonOperator.vue
- src/components/Select.vue
- src/components/Subscript.vue
- src/utils.js
- yarn.lock
This pr fixes an error while adding the first filter operator in aggregate stage
> Add correctly the first filter operator in aggregate stage

- src/components/Templates.vue
- src/store/rad.js
- src/utils.js
> fix(editor): validate template before import it

- src/components/AddressInformation.vue
- src/components/BalanceData.vue
- src/components/Community.vue
- src/components/DataRequest.vue
- src/components/LayoutTwoColumns.vue
- src/components/Templates.vue
- src/components/TransactionList.vue
- Remove unnecessary scroll in the following views: transactions, data request, community.
- Show template pagination only when needed
- Update items per page in template pagination
close #1247
> UI improvements

- electron-builder.json
- package.json
> build: set main linux category

- src/store/wallet.js
This pr shows a notification when the dr is broken and there are no partial results as a result of trying the data request.
> Show a notification when there is a general error trying the data request

- src/components/steps/WalletSeedBackup.vue
> feat(build): disallow copy mnemonics

- src/components/Editor.vue
- src/store/rad.js
> fix(editor): update correctly current stage on redo and undo

- src/components/RadonAggregateTallyScript.vue
- src/components/RadonOperator.vue
- src/components/RadonScript.vue
- src/components/Variables.vue
> fix(editor): trigger add operator on the button label

- src/components/CreateDataRequestForm.vue
- src/store/wallet.js
Update how deploy data request validation is made
> fix(deploy): update enoughFunds validation

- src/components/OperatorOutput.vue
- src/components/OperatorType.vue
- src/components/RadonOperator.vue
Rename first subscript operator options to see compatibility with input type until #1262 is solved.
> Rename first subscript operator options

- src/components/Select.vue
- src/components/Sidebar.vue
> set sidebar over other components

- src/components/AddressCardButton.vue
- src/components/EditorOperatorArgument.vue
- src/components/EditorStageScripts.vue
- src/components/OperatorOutput.vue
- src/components/RadonAggregateTallyScript.vue
- src/components/RadonOperator.vue
- src/components/RadonScript.vue
- src/components/Subscript.vue
- src/components/card/EditorAggregationsTally.vue
- src/components/card/EditorScript.vue
- src/store/rad.js
- src/store/uiInteractions.js
> Show partial results in subscript operators

- src/api.js
- src/components/AddressInformation.vue
- src/components/AddressList.vue
- src/components/Addresses.vue
- src/components/CompleteVariablesForm.vue
- src/components/ConfirmDataRequest.vue
- src/components/CreateDataRequestForm.vue
- src/components/FormInformation.vue
- src/components/Send.vue
- src/styles/element-variables.scss
- tests/unit/src/components/AddressInformation.spec.js
- tests/unit/src/components/AddressList.spec.js
- tests/unit/src/components/Addresses.spec.js
> Show transaction details when deploying a data request

- src/components/EditorToolBar.vue
- src/store/rad.js
- src/utils.js
- tests/unit/src/utils.spec.js
> fix(templates): avoid save id on export wallet

- src/components/EditorToolBar.vue
- src/store/rad.js
- tests/unit/src/components/EditorToolbar.spec.js
> Fix auto save template and remove save button

- src/App.vue
- src/components/AddressInformation.vue
- src/components/Notification.vue
- src/components/TransactionDetails.vue
- src/constants.js
- src/directives.js
- src/store/uiInteractions.js
- src/utils.js
This PR continues the work done in #1270 
Close #1257
> feat: create Notification component

- package.json
- src/components/EditorOperatorArgument.vue
- src/components/Select.vue
- tests/unit/src/components/EditorOperatorArgument.spec.js
- yarn.lock
> feat: add boolean argument as select

- src/components/Editor.vue
- src/components/EditorSource.vue
- src/components/EditorToolBar.vue
- src/components/RadonOperator.vue
- src/components/RadonScript.vue
- src/components/RenameTemplate.vue
- src/constants.js
- src/store/rad.js
- src/store/wallet.js
- src/styles/element-variables.scss
- tests/unit/src/components/EditorToolbar.spec.js
> Try dr switch review

- src/components/Select.vue
> fix(Select): add white background

- src/router.js
This pr fixes the redirection to 'wallet not found' when the wallet is running.
close #1267
> Fix wrong redirection to wallet not found

- src/components/EditorOperatorArgument.vue
- src/components/RadonOperator.vue
- src/components/Subscript.vue
- src/store/wallet.js
> Show error in operator when it breaks the data request

- src/components/EditorSettings.vue
> Add margin-bottom in variables' card

- package.json
Bump Sheikah's version to 0.2.0
> chore: bump version to 0.2.0

- src/store/rad.js
> Delete default variable when creating a new template

- src/components/CreateDataRequestForm.vue
- src/components/Send.vue
- src/styles/app.global.scss
> fix: allow write float numbers in fields

- src/components/ConfirmDataRequest.vue
- src/components/CreateDataRequestForm.vue
- src/components/DeployDataRequest.vue
- src/components/FormInformation.vue
> feat: remove tally fee

- src/components/Transaction.vue
- src/components/TransactionDetails.vue
> Style time-locked transactions and add time-locked status

- src/components/JsonTree.vue
- src/components/OperatorOutput.vue
- src/utils.js
- tests/unit/src/utils.spec.js
> Add function to simplify data request result 

- src/claimingDisclaimers.js
- src/components/card/Disclaimer.vue
- src/components/claiming/CreateWallet.vue
- src/components/claiming/WalletDisclaimer.vue
- src/components/claiming/WalletSeedBackup.vue
- src/router.js
> Add disclaimers to claiming process

- src/background.js
> Support copy paste in Electron

- src/background.js
- src/ipcHandlers.js
- src/store/wallet.js
> Fix close wallet when Sheikah closes

- src/constants.js
- src/store/wallet.js
- src/views/Transactions.vue
> Add confirmed and orphaned transactions notifications

- src/components/ConfirmDataRequest.vue
With this PR the commit and reveal fee is updated when confirming a dr 
Closes #1374
> fix: show commit and reveal fee when confirm a dr

- package.json
- src/App.vue
- src/background.js
- src/components/Community.vue
- src/components/UpdateNotification.vue
- src/constants.js
- src/ipcHandlers.js
- src/store/uiInteractions.js
- src/styles/element-variables.scss
- src/utils.js
- yarn.lock
This pr is a continuity of #1365
close #1357
> Auto download new Sheikah version and install it

- src/components/claiming/Countdown.vue
- src/router.js
Fix redirection when the user has completed the claiming process and re-lunch Sheikah.
Fix #1369
> Fix redirection in claiming process

- src/api.js
- src/components/claiming/UploadFile.vue
- src/utils.js
> fix(claiming-process): fix compatibility with current TGE scripts

- src/components/BalanceData.vue
- src/store/wallet.js
The values available and locked are printed right after changing unit
Closes #1394
> Fix: apply amount component to available and lock value

- src/App.vue
- src/components/TransactionDetails.vue
- src/store/uiInteractions.js
> Fix notification when addresses are copied

- src/store/wallet.js
- src/views/Transactions.vue
> Fix get info when changing wallet

- src/reducedClaimingDisclaimers.js
Remove disclaimer with title "Hey, listen"
> fix: remove disclaimer

- claiming_file_success.json
- src/background.js
- src/components/claiming/ClaimingInfo.vue
- src/constants.js
- src/utils.js
- tests/unit/src/utils.spec.js
> fix(claiming-process): transform nanowits from claiming in wits

- src/components/CreateDataRequestForm.vue
- src/components/NetworkStatus.vue
- src/components/Send.vue
- src/store/uiInteractions.js
- src/store/wallet.js
- src/views/Transactions.vue
fix #1381 
fix #1399 
fix #1396
> Fix: validate VTT and DR and correctly sort transactions

- src/components/claiming/ClaimingInfo.vue
- src/components/claiming/Countdown.vue
- src/components/claiming/DownloadFile.vue
- src/components/claiming/Instructions.vue
- src/components/claiming/UploadFile.vue
- src/components/claiming/Vesting.vue
- src/components/claiming/WalletEncryptionPassword.vue
- src/components/claiming/WalletSeedBackup.vue
- src/components/claiming/WalletSeedValidation.vue
- src/components/steps/WalletSeedBackup.vue
- src/components/steps/WalletSeedValidation.vue
- src/reducedClaimingDisclaimers.js
Updates copies in the claiming process
> Copies claiming process

- src/claimingDisclaimers.js
- src/components/claiming/Countdown.vue
- src/components/claiming/DownloadFile.vue
- src/components/claiming/Instructions.vue
- src/components/claiming/UploadFile.vue
- src/components/claiming/WalletSeedBackup.vue
- src/components/steps/WalletEncryptionPassword.vue
- src/components/steps/WalletSeedBackup.vue
- src/reducedClaimingDisclaimers.js
> Update claiming copies

- src/components/claiming/Countdown.vue
- src/constants.js
Add tutorial link at the end of the claiming process and update sheikah's url
> feat: add tutorial link and update url

- src/components/TransactionDetails.vue
- src/utils.js
- tests/unit/src/components/TransactionDetails.spec.js
- tests/unit/src/utils.spec.js
This PR shows the results of the reveals in a DR
> Show reveals and result

- src/components/Amount.vue
- src/components/InputsOutputs.vue
- src/components/Transaction.vue
- src/components/claiming/ClaimingInfo.vue
- src/components/steps/WelcomeForm.vue
- src/utils.js
This pr fixes the way the numbers are formatted and add it to the component Amount.
> Fix format numbers

- src/components/Amount.vue
- src/components/Send.vue
- src/components/claiming/ClaimingInfo.vue
- src/utils.js
- tests/unit/src/utils.spec.js
> Fix number format

- src/constants.js
- src/store/wallet.js
> chore: set default wit unit as wit

- src/components/CreateDataRequestForm.vue
- src/store/wallet.js
- tests/unit/src/components/CreateDataRequestForm.spec.js
> Fix: send number instead of string when necessary while sending data requests

- src/background.js
> Delete tray behavior in Sheikah

- src/api.js
- src/background.js
- src/components/CreateDataRequestForm.vue
- src/store/wallet.js
- tests/unit/src/components/CreateDataRequestForm.spec.js
- yarn.lock
> Fix get tally transaction

- src/components/CreateDataRequestForm.vue
- src/components/EditorToolBar.vue
- src/components/WelcomeBack/WalletList.vue
- src/store/rad.js
This pr fixes clearing the data request result (close #1498), fixes spelling issues (close #1502), and also adds a validation error in the consensus percentage field when creating a data request (close #1497).
> Fix small bugs

- src/components/NetworkStatus.vue
- src/store/wallet.js
> Show more detailed synchronization info

- src/components/AppendCurrency.vue
- src/components/CreateDataRequestForm.vue
- src/components/Send.vue
- src/constants.js
- src/store/wallet.js
- src/utils.js
> Make amount input change currency on click and add milliWit

- src/components/WelcomeBack/WalletList.vue
> Fix selected wallet in wallet list

- src/api.js
- src/components/NetworkStatus.vue
- src/components/WelcomeBack/WalletList.vue
- src/components/steps/WalletDescription.vue
- src/components/steps/WalletDisclaimer.vue
- src/components/steps/WalletEncryptionPassword.vue
- src/components/steps/WalletImport.vue
- src/components/steps/WalletSeedValidation.vue
- src/router.js
- src/store/wallet.js
- tests/unit/src/components/steps/WalletDescription.spec.js
> Add wallet name feat

- .env_example
- .gitignore
- src/background.js
> chore: allow set wallet log level with env var

- src/components/FormInformation.vue
- src/store/wallet.js
This PR updates the `create_vtt` JsonRPC method modified in https://github.com/witnet/witnet-rust/pull/1717.
> fix: update create_vtt output param

- src/components/ConfirmDataRequest.vue
- src/components/CreateDataRequestForm.vue
- src/components/DeployDataRequest.vue
- src/components/FormInformation.vue
- src/components/Send.vue
- src/store/wallet.js
- tests/unit/src/components/Balance.spec.js
- tests/unit/src/components/CreateDataRequestForm.spec.js
Show error when the balance is not enough due to a high absolute fee
> Show error when balance is not enough due to a high absolute fee

- package.json
- src/api.js
- src/components/ExportXprv.vue
- src/components/FileUploader.vue
- src/components/PasswordValidation.vue
- src/components/Sidebar.vue
- src/components/steps/DecryptXprv.vue
- src/components/steps/ImportXprv.vue
- src/components/steps/RepeatedWalletDisclaimer.vue
- src/components/steps/WalletDescription.vue
- src/components/steps/WalletEncryptionPassword.vue
- src/components/steps/WalletImport.vue
- src/components/steps/WalletSeedTypeSelection.vue
- src/router.js
- src/services/SyncingTimeEstimator.js
- src/store/wallet.js
- tests/unit/src/components/FileUploader.spec.js
- yarn.lock
> Allow import and export xprv

- src/background.js
- src/ipcHandlers.js
- src/store/wallet.js
> Only close the wallet when Sheikah has run it

- src/store/wallet.js
> fix: clear and refresh session timeout

- src/styles/app.global.scss
> chore: disable user-select on images

- src/background.js
> fix: running wallet on cancel update

- src/api.js
- src/components/ConfirmDataRequest.vue
- src/components/CreateDataRequestForm.vue
- src/components/FormInformation.vue
- src/components/Send.vue
- src/components/TransactionList.vue
- src/store/wallet.js
- src/utils.js
- src/utils/BigNumber.js
- tests/unit/src/components/CreateDataRequestForm.spec.js
- tests/unit/src/components/TransactionList.spec.js
- tests/unit/src/services/BigNumber.spec.js
> feat: allow send and receive strings when creating a transaction

- .eslintignore
- .prettierignore
- Ignore linter in locales folder
> chore. ignore linter in locales folder

- src/components/AddressInformation.vue
- src/components/Transaction.vue
- Remove italic styles to improve readability
close #1590
> fix(Transaction): improve readability of addresses

- src/components/FileUploader.vue
- src/components/steps/ImportXprv.vue
- src/styles/theme.scss
> fix: validation error in import xprv file

- src/api.js
- src/components/Amount.vue
- src/components/SendValueTransfer.vue
- src/components/Transaction.vue
- src/components/TransactionDetails.vue
- src/components/TransactionList.vue
- src/locales/en.json
- src/locales/es.json
- tests/unit/src/components/Transaction.spec.js
> Show pending confirmation status in transaction

- src/components/Version.vue
- src/components/steps/WelcomeForm.vue
- src/styles/theme.scss
- src/views/Settings.vue
- src/views/WelcomeBack.vue
> feat: show Sheikah version in wallet list view

- src/components/Address.vue
- src/components/AddressInformation.vue
- src/components/GeneratedTransaction.vue
- src/components/InputsOutputs.vue
- src/components/Transaction.vue
- tests/unit/src/components/Address.spec.js
- tests/unit/src/components/AddressInformation.spec.js
- tests/unit/src/components/InputsOutputs.spec.js
- tests/unit/src/components/Transaction.spec.js
- Implement an Address component and refactor to avoid duplication
> ref(Address): implement Address component to unify logic and style

- src/components/AddressCard.vue
- src/components/Transaction.vue
- src/styles/theme.scss
> fix(style): pending confirmation and address border theme color

- src/components/card/TemplateCard.vue
> fix(templateCard): bigger hover area to show dropdown options

- src/router.js
> fix(router): do not redirect to wallet list if session id

- src/components/AddressInformation.vue
> Fix copied tooltip delay

- src/api.js
- src/views/Transactions.vue
- tests/unit/src/components/SettingsNotificationsList.spec.js
> Order transactions by timestamp and time-lock

- src/router.js
> fix(walletList): avoid error loading wallets

- src/App.vue
- src/api.js
- src/components/DescriptionModal.vue
- src/components/NetworkStatus.vue
- src/components/Sidebar.vue
- src/components/steps/WalletDescription.vue
- src/locales/en.json
- src/locales/es.json
- src/store/uiInteractions.js
- src/store/wallet.js
> Show wallet description

- src/components/NetworkStatus.vue
> fix: show connected to node address when it is connected

- src/api.js
- src/components/SendValueTransferForm.vue
- src/locales/en.json
- src/locales/es.json
- src/store/wallet.js
- src/styles/element-variables.scss
- src/styles/theme.scss
> feat: allow sending vtt with timelock

- src/components/steps/DecryptXprv.vue
- src/components/steps/ImportXprv.vue
- src/locales/en.json
- src/locales/es.json
- src/store/wallet.js
> fix: show password validation error as a message not an alert

- package.json
Sheikah v1.9.6 includes:
- Fix auto-update when the release is being created by GitHub-actions
- Add data request examples in newly created wallets
- Allow renaming a wallet from settings
- Delete wallet from settings
- Allow selecting weighted or absolute fee to create VTT
- Update witnet-radon-js to 0.8.5
- FTU download only compatible version
> chore: bump 1.9.6

- src/components/Address.vue
- src/components/AddressInformation.vue
- src/components/Addresses.vue
- src/components/GeneratedTransaction.vue
- src/components/LayoutTwoColumns.vue
- src/components/Transaction.vue
- src/components/TransactionDetails.vue
- src/constants.js
- src/styles/app.global.scss
- tests/unit/src/components/Address.spec.js
- tests/unit/src/components/Transaction.spec.js
> feat: add external link to the block explorer for the witnet tx

- .github/workflows/build.yaml
- .github/workflows/lintAndTest.yaml
- .github/workflows/release.yaml
- package.json
- tests/unit/src/components/FileUploader.spec.js
> chore(deps): set node engines

- .github/workflows/build.yaml
- .github/workflows/lintAndTest.yaml
- .github/workflows/release.yaml
- package.json
More info: actions/virtual-environments#4856
> fix(ci): bump node version to support windows server 2022 update

- package.json
- src/components/EditorSource.vue
- src/components/EditorStageSources.vue
- src/locales/en.json
- src/locales/es.json
- src/store/rad.js
- src/utils.js
- tests/unit/src/components/EditorSource.spec.js
- yarn.lock
This pr add support in Sheikah for POST kind sources. This must be tested with [witnet-radon-js #85](https://github.com/witnet/witnet-radon-js/pull/85).
close #1788
> feat(EditorSource): add support for POST requests

- src/background/constants.ts
- src/background/utils/overwriteWitnetNodeConfiguration.ts
- tests/unit/src/background/utils/overwriteWitnetNodeConfiguration.spec.ts
> feat(chore): update witnet public nodes

- src/components/WelcomeBack/WalletList.vue
> fix(WalletList): avoid changing selected wallet on get walletInfos

- src/components/DeleteWalletConfirmation.vue
- src/components/DeployDataRequest.vue
- src/components/DescriptionModal.vue
- src/components/LogoutModal.vue
- src/components/RenameConfirmation.vue
- src/components/ResyncConfirmation.vue
- src/components/SendValueTransfer.vue
> feat(ui): update closing behaviour in modals

- package.json
```
Version: 1.11.4
Release type: patch
Criticality: non-critical
```
Relevant features included in this release:
- [feat(config): overwrite outdated public node url on new sheikah update](https://github.com/witnet/sheikah/commit/a8a75fd92e0f731a9373e01c733c7521d22a4a36)
- [fix(chore): handle wallet version download](https://github.com/witnet/sheikah/commit/be2fe5d0c2ead390068d2edde3cd7b3696f7605c)
- [fix(ui): allow using 0 index in getString from array](https://github.com/witnet/sheikah/commit/75f79d6a470e60340290c1630df97da9e5327c42)
- [feat(EditorSource): add support for POST requests](https://github.com/witnet/sheikah/commit/b3276840bf00c11bb526346b2df5021f95375d46)
- [feat(estimatedFee): allow selecting estimated fees](https://github.com/witnet/sheikah/commit/fb26d7bc895d1b18303e130c7 …
> chore: bump 1.11.4

- .github/workflows/build.yaml
- package.json
- yarn.lock
This reverts commit 0ded6906674eeaa18910685f9605b5dba14321b2.
> Revert "chore: disable macos build until vue3 upgrade is merged"

- src/components/Fieldset.vue
- src/components/RadonScript.vue
> fix(style): handle overflow in urls

- package.json
- yarn.lock
- Fix radon `sort` operator
- Fix radon `asString` operator
> chore: upgrade to witnet-radon-js@0.11.0

- src/components/SendTransaction/SetFee.vue
- src/store/wallet.js
Fix #1864 
Rel https://github.com/witnet/witnet-rust/pull/2385
> fix: prevent internal keychain from skipping indexes
