witnet/sheikah

- package.json
- tsconfig.json
Fixes `typecheck` task present in `package.json`
- Now the compiler does not emit output when the task is run
- Added option `baseUrl` to tsconfig.json so non-relative imports in
test files are found when type-checking
Just run `yarn typecheck` or `yarn typecheck --watch`
> Fixes typecheck task

- app/lib/storage/storageBackend.ts
- tslint.json
+ Interface names don't need to start with "I" anymore
+ Renamed interface `IStorageBackend` → `StorageBackend`
>  Change interface name linting preference 

- test/app/lib/storage/encryptedStorage.spec.ts
Tests proving the sucess of `Promise<void>` don't really need to use `expect()` at all.
If they resolve and don't throw any exceptions, they're just OK!
> Improve EncryptedStorage tests

- package.json
- typings/secp256k1/index.d.ts
Changes:
- Add typings for the [secp256k1](https://github.com/cryptocoinjs/secp256k1-node/blob/master/API.md) library API
- Change `lint` task in `package.json` to mimic the `precommit` task, because the first was succeeding when the second was not
> Secp256k1 typings

- docs/styleguide.md
There's a point that says `Do not use semicolons` but all the examples had semicolons
> Remove semicolons from examples

- package.json
Add an option to the `typecheck` task to read project configuration from `tsconfig.json` file.
> Specify project in typecheck task

- docs/CONTRIBUTING.md
These guidelines are based on the [AragonJS contributing guidelines](https://wiki.aragon.one/submodules/aragon.js/CONTRIBUTING/), published under the [Creative Commons Zero v1.0 Universal License](https://github.com/aragon/aragon-wiki/blob/master/LICENSE).
This closes #52.
> Add contributing guidelines for newcomers

- docs/STYLEGUIDE.md
- tslint.json
Relax [lint rule](https://palantir.github.io/tslint/rules/only-arrow-functions/) for arrow functions and update styleguide accordingly. Please, add your comments :)
Closes #54
> Relax lint rule for arrow functions

- docs/PULL_REQUEST_TEMPLATE.md
Add check for reading CONTRIBUTING document in PR template, just like the above checks do everytime a new pull request is created.
> Add check for reading CONTRIBUTING document in PR template

- .travis.yml
- README.md
- commitlint.config.js
- package.json
As suggested by @mariocao and discussed in #63, this PR adds [commitizen][commitizen] to our project. It also adds [commitlinter] to  guarantee that GitHub rejects PRs with commit messages not abiding by our guidelines.
All commits should now abide by Angular's [conventional changelog convention][convention].
No actual testable code was modified—only configuration files.
[commitizen]: https://github.com/commitizen/cz-cli
[commitlinter]: https://github.com/marionebl/commitlint
[convention]: https://github.com/conventional-changelog-archived-repos/conventional-changelog-angular/blob/master/convention.md
> Add commitizen and commitlinter

- docs/CONTRIBUTING.md
Commits verification is needed while merging a PR, but missed in contributing guide.
> add contributing guide for signing commits

- config/tsconfig.json
fix #97
Should this not be fixed, results of compilation process would be placed inside config directory, which may be not the right place for them to be. No tests needed, it is just a path fix in a configuration file.
> fix(tsconfig): fix output directory in tsconfig.json

- package.json
the command was looking for tsconfig.json in the config directory, and
we moved it back to the root a few commits ago.
Fix tslint command that runs as part of `tslint-staged` task.
> build(npm): fix tslint command in lint-staged hook

- app/lib/crypto/key/privateKey.ts
- app/lib/crypto/key/publicKey.ts
> fix(crypto): expression comparing buffer is always false

- .travis.yml
- package.json
- yarn.lock
Some rules in tslint require *type checking* (aka: pass the tsconfig path option to tslint) in order to work, see palantir/tslint#2933. Problem is that Codacy/Hound don't support passing that flag to tslint so basically, some rules are not being check in those services. This PR adds a new step to travis to lint the project including these rules that need type checking.
[cont]: https://github.com/witnet/sheikah/blob/master/docs/CONTRIBUTING. …
> Lint travis

- tsconfig.json
As explained at #134, we should use `es2018` in the TypeScript compiler to benefit from the modern Javascript kool-aid.
No tests as no app code has been modified.
fixes #134
> build(tsconfig): make the ts compiler use 'es2018' instead of 'es6'

- app/lib/crypto/address/p2pkh.ts
- app/lib/utils/utils.ts
- test/app/lib/utils/utils.spec.ts
As suggested by @aesedepece added a method to swap keys for values and replaced an unnecessarily long switch statement using a call to kvSwap
> refactor(address): remove unnecessary switch statement

- docs/STYLEGUIDE.md
> docs(style): comment styling that should be followed

- app/renderer/ui/components/signup/style.scss
- package.json
- yarn.lock
This change adds a simple sass formatter in order to harmonize the format of the scss files.
No tests were required because it only adds a new dependency for the formatter.
> build(scssfmt): add sass formatter

- app/common/env.ts
- app/main/ui.ts
- config/paths.js
- package.json
This fixes (again) a problem María detected when running `yarn start`. This was fixed #169 but was applied to the `main/index.js`, and since #180 that file no longer exists and has been replaced by `main/index.ts`
> fix(yarn start): port fix for appHtml not found to main/index.ts

- app/common/ipc-protocol.ts
- app/common/ipc.ts
- app/common/serializers/json.ts
- app/main/api/handlers/echo.ts
- app/main/api/handlers/error.ts
- app/main/api/handlers/index.ts
- app/main/api/handlers/nop.ts
- app/main/api/handlers/ping.ts
- app/main/api/index.ts
- app/main/api/routes.ts
- app/main/crypto/keyPath.ts
- app/main/index.ts
- app/main/ipc.ts
- app/main/system.ts
- app/renderer/api.ts
- app/renderer/ipc.ts
- app/renderer/store/configureStore.development.ts
- app/renderer/store/configureStore.production.ts
- config/tsconfig.json
- test/__stubs__/ipcRenderer.ts
- test/__stubs__/serializers.ts
- test/app/common/ipc-protocol.fixtures.ts
- test/app/main/api/index.spec.ts
- test/app/renderer/api.spec.ts
- test/setup.js
add an ipc client to be used to interact with handlers defined in Electron's Main process.
this client follows a **stateless design**, that is, on sending a request the client will bound once to a special and unique "reply channel" that will be used by the Main process to univocally send the response for that request. if there's any problem parsing or decoding the request, the response will be sent to an special "dead letter" channel, is responsability of the frontend (not the client) to subscribe to that channel in …
> feat(ipc-renderer): stateless ipc client

- app/renderer/ui/app.global.scss
prefix antd overrides with `body` tag so our selectors override antd'sotherwise the opposite happens in the production build because our global styles are injected before antd's
fixes #203
> fix(css): prefix antd overrides with app id

- app/common/runtimeTypes/storage/wallets.ts
- app/main/api/handlers/index.ts
- app/main/api/handlers/newMnemonics.ts
- app/main/api/routes.ts
- app/main/appState.ts
- app/renderer/api/index.ts
- app/renderer/api/newMnemonics.ts
- test/app/main/api/handlers/newMnemonics.spec.ts
- test/app/renderer/api/newMnemonics.spec.ts
This pull request adds the functionality of creating new mnemonics in order to create new wallets.
The main process:
- uses the crypto library to get new mnemonics
- updates the application state with the unconsolidated wallet created from these new mnemonics
- defines a handler to export this functionality to the renderer process through the IPC API
The renderer process:
- defines a function that abstracts from the newMnemonics IPC API call and returns the generated mnemonics
[cont]: …
> feat(api): create new mnemonics

- app/renderer/index.tsx
- app/renderer/services.ts
- app/renderer/store/configureStore.development.ts
- app/renderer/store/configureStore.production.ts
This leverages `redux-thunk` extensibility to inject a "services" object into action creator functions. This object only provides apiClient at the moment, but it can hold whatever other objects we may need to use in Redux action creators in the future.
More info about the solution can be found in #239.
fix #239
> feat(store): expose ipcRenderer API client to Redux

- app/common/ipc-protocol.ts
- app/main/api/handlers/echo.ts
- app/main/api/handlers/index.ts
- app/main/api/handlers/nop.ts
- app/main/api/index.ts
- app/renderer/api/index.ts
- test/app/common/ipc-protocol.fixtures.ts
- test/app/renderer/api.spec.ts
- test/app/renderer/api/newMnemonics.spec.ts
re #245
This PR refactors IPC params from Array<JsonSerializable> to JsonSerializable. This change is introduced mainly to avoid using io-ts/tuple to wrap every runtime type.
> refactor(ipc): refactor ipc params to be JsonSerializable, not array

- app/common/runtimeTypes/index.ts
- app/common/runtimeTypes/ipc/wallets.ts
- app/main/api/handlers/validateMnemonics.ts
- app/main/utils/utils.ts
- test/app/main/api/handlers/validateMnemonics.spec.ts
This refactors #222 (`validateMnemonics` handler) as a promise chain.
> refactor: newMnemonics handler

- app/common/runtimeTypes/ipc/wallets.ts
> refactor(rt-types): rename importSeedError to match style guide

- app/renderer/actions/loginForm.ts
- app/renderer/constants/urls.ts
- app/renderer/index.tsx
- app/renderer/routes.tsx
- app/renderer/store/configureStore.development.ts
- app/renderer/store/configureStore.production.ts
- app/renderer/ui/containers/Forms.tsx
- app/renderer/ui/containers/LoginForm.tsx
- app/renderer/ui/containers/Root.tsx
- app/renderer/utils/propsRoute.tsx
LoginForm container now receives services by props. This logic substitutes the previous use of the thunk middleware and it results in a clearer flow in the process of unlocking a wallet.
> refactor(login-form): services passed as props to loginForm container

- app/main/api/handlers/getWallet.ts
- app/main/storage/jsonAesLevel.ts
The key used before was wrong, as it was the wallet id and not the string literal "wallet".
Additionally, some storage types have been simplified following the example of the encryptWallet
handler.
> fix(handler): use "wallet" as the key to get wallet from AES storage

- app/main/index.ts
- app/main/system.ts
Closes #375
This commit introduces changes that removes `debug` messages shown in
the console for production builds.
> refactor(log): set production log level explicitly

- app/main/api/handlers/importSeed.ts
The removal of mnemonics from unconsolidated wallet in an intermediate step of the wallet form left an inconsistent app state when moving across the application. Mnemonics are now kept in the unconsolidated wallet until the encryptWallet step, where the whole unconsolidated wallet is removed from the app state.
fix #370
> fix(wallet-form): keep mnemonics in unconsolidated wallet until the encrypt wallet step

- app/main/api/handlers/importSeed.ts
- app/renderer/ui/containers/LoginForm.tsx
- test/app/main/api/handlers/importSeed.spec.ts
Mnemonics matching will be performed when needed (in the new seed logic) in the frontend. This allows us to reuse the `importSeed` handler to create a seed and to import a seed and fixes #373 
> fix(wallet-form): remove match mnemonics check in importSeed handler in the backend 

- app/renderer/constants/urls.ts
- app/renderer/index.tsx
- app/renderer/routes.tsx
- app/renderer/services.ts
- app/renderer/ui/components/commonTypes.ts
- app/renderer/ui/components/main/index.tsx
- app/renderer/ui/components/main/sections/attestations/index.tsx
- app/renderer/ui/components/main/sections/blockExplorer/index.tsx
- app/renderer/ui/components/main/sections/community/index.tsx
- app/renderer/ui/components/main/sections/index.tsx
- app/renderer/ui/components/main/sections/smartContracts/index.tsx
- app/renderer/ui/components/main/sections/smartContracts/tabs/easyComposer/index.tsx
- app/renderer/ui/components/main/sections/smartContracts/tabs/marketplace/index.tsx
- app/renderer/ui/components/main/sections/smartContracts/tabs/myContracts/index.tsx
- app/renderer/ui/components/main/sections/smartContracts/tabs/proEditor/index.tsx
- app/renderer/ui/components/main/sections/wallet/index.tsx
- app/renderer/ui/components/main/sections/wallet/tabs/coins/index.tsx
- app/renderer/ui/components/main/sections/wallet/tabs/receive/index.tsx
- app/renderer/ui/components/main/sections/wallet/tabs/send/index.tsx
- app/renderer/ui/components/main/sections/wallet/tabs/transactions/index.tsx
- app/renderer/ui/components/sidebar/sidebarLink.tsx
- app/renderer/ui/components/topBar/topBarLink.tsx
- app/renderer/ui/containers/Main.tsx
- app/renderer/ui/containers/WalletForm.tsx
- app/renderer/utils/propsRoute.tsx
Main container now holds the main routing logic (both the sections routing and the tabs routing). The main container and not the main page component is the one that is being rendered from the routes. Main container is now pre-connected with redux for future use.
Additionally, URLs used under /main have been moved to the URL constants file (re #329). Also, the refactor of the smart contracts section fixes #383.
[style]: …
> feat(container): move main section router to main container

- app/common/runtimeTypes/ipc/address.ts
- app/renderer/api/generateAddress.ts
- app/renderer/api/index.ts
- test/app/renderer/api/generateAddress.spec.ts
- test/app/renderer/api/getWallet.spec.ts
It adds the API renderer function to request the generation of an address from the front-end side to the back-end corresponding handler. Tests are added for this function.
> feat(api): add generateAddress API renderer function

- app/common/runtimeTypes/ipc/wallets.ts
- app/main/api/handlers/getWallet.ts
At the promise chain of the `getWallet` handler, we now have different functions for retrieving the wallet from the database and for validating the type of the retrieved wallet. Fixes #433. 
> fix(handler): fix bug when handling errors in getWallet handler

- app/renderer/ui/components/main/sections/wallet/tabs/receive/index.tsx
- app/renderer/ui/components/main/sections/wallet/tabs/transactions/index.tsx
This commit replaces placeholders in dropdowns with the actual final copies in the sections that are already implemented.
Future sections will need to implement their own copies, which I set forth in the comments of issue #445.
No tests as this has no impact to business logic.
close #445
> feat(dropdowns): put final copies for options in dropdowns

- app/renderer/ui/components/main/sections/wallet/tabs/receive/index.tsx
Addresses are not sorted anymore by creation date but instead, the array of final keys is reversed
(as new addresses are just pushed at the end of the array).
fix #464
> fix(address): fix logic where addresses and prefilled data were combined

- src/components/Transactions.vue
- src/store/wallet.js
The method for setting the list of addresses when generating a new one has been divided into two different methods. The offset of addresses that can be listed is 25, there is a need for checking the argument `offset` to retrieve more than 25 addresses from the Wallet.
> Fix get addresses

- src/components/Button.vue
- src/components/Send.vue
- src/components/WelcomeBack/UnlockWallet.vue
This PR adds a submit on pressing the enter key in the send component and in the unlock wallet component. This entails better keyboard accessibility.
> Add submit on pressing enter

- src/components/Carousel.vue
- src/components/RadonOperator.vue
- src/components/RadonStage.vue
- src/components/Templates.vue
- src/components/Variables.vue
- src/components/WelcomeBack/WalletList.vue
- src/components/card/TemplateCard.vue
- src/views/WelcomeBack.vue
This PR fixes the following css errors:
- **Welcome back view**: remove always visible scroll, add id as default name for wallet and adjust sizes to avoid overflow.
- **Template list**: adjust size of cards to fit content correctly.
- **Editor**: remove button background in firefox and remove always visible scrolls.
Close # 861
Close #862 
Close #863
> Css polish

- src/store/wallet.js
This PR clears errors when a result in the wallet call is provided.
> Clear error when wallet call result is provided

- ci/initializeWallet.sh
This will keep trying to download the witnet release until it works.
> chore: retry curl if github is down

- src/background.js
Remove electron toolbar when environment is set to production.
> feat: remove electron toolbar in production environment

- src/components/claiming/DownloadFile.vue
- src/store/wallet.js
This PR saves the claiming process state in local storage to be able to know if the user has generated the addresses correctly.
> Generated addresses state

- src/store/wallet.js
Notifications are not shown anymore if the socket is not ready or if there is a connection problem. It redirects instead to the warning view.
> Fix notifications when socket not ready

- src/utils.js
- tests/unit/src/utils.spec.js
This PR fixes the ```standardizeWitUnit``` function to not remove zero digits if the unit provided is nanoWit.
> Fix standardizeWitUnits function

- src/background.js
Disable shortcuts using a hidden menu binding the shortcut we want to disable to an option. This aims to remove the globalShortcut problems.
> fix: disable shortcuts using hidden menu

- src/components/AddressList.vue
Fix remove wrong scroll behavior in address list when the number of addresses in greather than 26(number of addresses that fits without scroll).
close  #1125
> fix(address-list): remove wrong scroll behavior

- src/background.js
Update the wallet configuration file path used by the bundle. It solves `stdout: HEADS UP! No configuration specified/found. Using default one!` error.
> Fix wallet path in bundle

- src/components/steps/WalletSeedTypeSelection.vue
It deletes the back button in ```WelcomeForm``` view when there is no wallet created.
> Delete the back button in WelcomeForm view when there is no wallet created.

- src/components/card/TemplateCard.vue
This pr fixes the click event in the template card so the user can edit on click in the full card except when clicking the dropdown button.
close #1271
> Edit template clicking in the template card

- src/router.js
This pr allows opening the wallet right after the session id is found and also fixes the redirection when the wallet info is found.
close #1340
> Fix redirection when wallet infos are found and time to open the wallet

- src/claimingDisclaimers.js
This PR deletes the description that was included twice in the claiming process.
Closes #1370
> fix: delete repeated description

- src/components/claiming/WalletSeedBackup.vue
- src/components/steps/WalletSeedBackup.vue
This PR disable the copy of the seed phrase in the claiming process.
Closes #1372
> fix: disable copy mnemonics in claiming process

- src/components/Amount.vue
- src/components/Transaction.vue
Some tx where set as several addresses but actually was just one repeated, now it shows only the address
Closes #1397
> Fix: not show several addresses if only one repeated

- src/components/Transaction.vue
> fix: show transactions with 0 inputs as "from genesis"

- src/views/Transactions.vue
> fix: sort transactions by time-lock and creation date

- README.md
- src/background.js
As it is currently impossible to see logs on certain platforms, the wallet can get a slight performance boost by moving the log level to info. Developers can still use the trace log level by setting it in witnet.toml or setting the environment variable `RUST_LOG=witnet=trace` when starting sheikah.
There are 3 ways to set the log level of the wallet, in order:
* `[log] level = "info"` in witnet.toml
* RUST_LOG environment variable
* `--trace`, `--debug` command line arguments when starting wallet
The `--trace` flag always forces the log level to trace, so it is impossible to change it to info. The default log level in witnet.toml is info, so removing this flag will set the log level to info.
> chore: remove --trace flag from wallet

- src/components/AppendUnit.vue
- src/components/CreateDataRequestForm.vue
- src/components/Send.vue
- src/store/wallet.js
- tests/unit/src/components/CreateDataRequestForm.spec.js
- Lock unit change in fee field in Send.vue component
- Lock unit change in fee field in CreateDataRequestForm.vue component
- Use nanotWit as default currency
close #1597
> feat: use nanoWit as static unit in fee field

- src/store/wallet.js
- Clear templates before close wallet session to avoid see them after open a different wallet
> fix(TemplateList): clear templates after close session

- package.json
- src/App.vue
- src/components/DeployDataRequest.vue
- src/components/EditorToolBar.vue
- src/components/SettingsLanguage.vue
- src/components/Templates.vue
- src/components/card/TemplateCard.vue
- src/constants.js
- src/plugins/i18n.js
- src/store/rad.js
- src/store/wallet.js
- tests/unit/src/components/SettingsLanguage.spec.js
- tests/unit/src/utils.spec.js
- yarn.lock
This PR have to be merged after [witnet#witnet-radon-js/44](https://github.com/witnet/witnet-radon-js/pull/44) and witnet-radon-js v0.8.2 is released.
- Upgrade `witnet-radon-js` to 0.8.4. Now Radon class accepts a locale argument to set the language of the descriptions. Also, expose a method `setLocale`, which we call to update the language of the current template.
- Simplify language settings flow. Now we store the locale, and we derive the language from it instead of doing it the other way around. This change makes it easier to add specific country locales in the future.
> Update witnet-radon-js and simplify SettingsLanguage

- .github/workflows/build.yaml
- .github/workflows/lintAndTest.yaml
- .github/workflows/release.yaml
- README.md
- scripts/notarize.js
- src/background.js
- vue.config.js
close #1659 
This PR adds two new github actions: build and release.
- `build` is triggered on every pull request. It tries to build Sheikah on `macos-latest`, `ubuntu-latest` and `windows-latest`.
- `release` is triggered when someone pushes into master. This action checks if the commit name and the tag name and then it drafts a new release.
>  ci(gh-actions): setup automatic builds and releases

- src/components/SendValueTransferForm.vue
- src/components/SettingsLanguage.vue
- src/components/steps/WalletBirthdate.vue
- src/components/steps/WalletImport.vue
- src/constants.js
- src/locales/en.json
- src/locales/es.json
- src/plugins/element.js
- src/store/wallet.js
- src/styles/element-variables.scss
- styleguide/scripts.js
This pr implements the suggestions from discussion #1701. 
The element-UI locale updates itself when the language changes and the date-picker input is hidden now behind the advance options button.
> fix: improve timelock ux

- src/background.js
It allows new versions of sheikah to update to new versions of witnet-rust
> feat: allow to set supported witnet-rust version in code

- src/background/walletManager.ts
This fixes a misleading log line that appears after opening the sheikah appimage:
```
Fetching release from: https://api.github.com/repos/witnet/witnet-rust/releases/tags/1.5.0
```
This happens when 1.5.3 version of the wallet is already installed, version 1.5.0 is logged there because it is the one hardcoded in the sheikah code, but it is not downloaded. This PR will print this line in that case instead:
```
Latest wallet version 1.5.3 already installed
```
> feat: improve logs about downloading wallet

- src/background/constants.ts
The estimation fee was introduced in witnet-rust `1.5.3`. If we target the `1.5.0`, Sheikah can't estimate the fees using the wallet.
> chore: use witnet_rust 1.5.6 as min version

- .github/workflows/build.yaml
Python 2.7 is deprectaed and can't be used in setup-python.
More info: https://github.com/actions/setup-python/issues/672
> ci: use python@3.11 in build workflow

- .github/workflows/release.yaml
- build/entitlements.mac.plist
- electron-builder.json5
- package.json
- pnpm-lock.yaml
Fixes error building Sheikah for mac intel
> chore: update electron and mac build target

- electron/main/index.ts
Fixes error in mac intel devices ```ERROR:gl_display.cc(497)] EGL Driver message (Error) eglQueryDeviceAttribEXT: Bad attribute.``` when running app
> fix: mac intel error `eglQueryDeviceAttributeXT: Bad attribute`
